### PR TITLE
Bump to latest version

### PR DESCRIPTION
**Pull request by skjolber**
Bump to latest version the library. 

I've added some TODOs where I was unsure how to migrate the code.

### CODE REVIEW

**Comment by lessthanoptimal** [comment]
I'm afraid to ask, but did you notice the SNAPSHOT branch? i kept on forgetting to merge in SNAPSHOT to master. In other projects I've just deleted master as there's no point of keeping a "stable" branch when you can just use tags.

**Comment by skjolber** [comment]
@lessthanoptimal I did not. I've rebased but there si a lot of conflicts. This is quite disappointing, and I don't have time to fix it.

Don't overthink the branching, use what everyone else is doing, so misunderstandings do not happen. Sounds like you want a master branch for releases + develop for development where develop also is  the primary branch (so github shows the develop branch when people visit your page). At least that would have prevented this mess.

**Comment by lessthanoptimal** [comment]
@skjolber I'm going to fix the branches now. I had done exactly what you described on other projects, but missed updating this one. Having a stable and developmental branch used to be more common, but was never a really good idea. Especially if you rarely update the stable branch... Sorry for the confusion! I know this wasn't a trivial PR!

Did you do a straight forward upgrade of BoofCV or did you include other improvements? If there are other improvements I can try to bring those over to the new code. SNAPSHOT is up-to-date with the latest version of BoofCV.

**Comment by skjolber** [comment]
@lessthanoptimal sounds good. No new functions were added, this was a straight forward upgrade.

**Pull request closed without merging**
